DROP TABLE IF EXISTS food;

CREATE TABLE work.food (
  id INT NOT NULL AUTO_INCREMENT,
  description VARCHAR(45) NOT NULL,
  votes INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE(id ASC) VISIBLE
);

